[package]
name = "rupar_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"

[build-dependencies]
cc = "1.0"
rust_parser = { path = "../macro/." }