[package]
name = "templated_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
cc = "1.0"
proc-macro2 = "1.0.103"
cxx-build = "1.0"
