[package]
name = "cmake_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"

[build-dependencies]
cc = "1.0"
cxx-build = "1.0"
cmake = "0.1.31"

[features]
default = ["lib64", "omp"]
lib64 = []
lib = []
cuda = []
omp = []
