[package]
name = "test_krokkos"
version = "0.1.0"
edition = "2024"

[dependencies]
krokkos = {path = "../krokkos/." }
cxx = "1.0"

[build-dependencies]
krokkos-build = {path = "../krokkos/build/." } 
