name: Outside Run Test

on:
  push:
    branches: [ "main", "draft" ]
  pull_request:
    branches: [ "main", "draft" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Kokkos installation
      run: bash kokkos-install.sh
    - name: Build
      working-directory: ./test_poc_interop
      run: cargo build --verbose
    - name: Run extern proj using poc_interop
      working-directory: ./test_poc_interop
      run: cargo run --verbose
