name: Outside Run Test

on:
  push:
    branches: [ "main", "draft" ]
  pull_request:
    branches: [ "main", "draft" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./test_krokkos
      run: cargo build --verbose
    - name: Run extern proj using krokkos
      working-directory: ./test_krokkos
      run: cargo run --verbose
