name: Tests

on:
  push:
    branches: [ "main", "draft" ]
  pull_request:
    branches: [ "main", "draft" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./krokkos
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./krokkos
      run: cargo test --verbose
